#!/bin/bash

if [[ ! $# -eq 1 ]] ; then
    echo "Invalid number of arguments: $#"
    exit 1
fi

./runtime/linkxi.sh $1

if [ $? -eq 0 ] 
then
  ./a.out
  exit 0
else 
  echo "Runtime error: $?"
  exit 1
fi
