#!/bin/bash

if [[ $# -eq 0 ]] ; then
    exit 1
fi

interpret () {
    java -cp ./interpreter/build/:./interpreter/lib/java_cup.jar:/interpreter/lib/jflex.jar edu.cornell.cs.cs4120.xic.ir.interpret.Cli $1
}

for file in "$@"
do
    interpret "$file"
done
